import type { Metadata } from "next";
import "./globals.css";
import { ppneuemontreal } from "./font";
import Footer from "@/components/sections/footer";
import AosInitialiser from "./aos-initialiser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppneuemontreal.className} antialiased bg-white overflow-x-hidden`}
      >
        <AosInitialiser />
        {children}
        <Footer />
      </body>
    </html>
  );
}
