import type { Metadata } from "next";
import "./globals.css";
import { ppneuemontreal } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ppneuemontreal.className} antialiased bg-white px-6 xl:px-0`}
      >
        {children}
      </body>
    </html>
  );
}
